
import streamlit as st
st.set_page_config(page_title="QuLab", layout="wide")
st.sidebar.image("https://www.quantuniversity.com/assets/img/logo5.jpg")
st.sidebar.divider()
st.title("QuLab")
st.divider()
st.markdown("""
In this lab, we present a "Model Card Generator" application, an interactive tool designed to help users understand, visualize, and analyze datasets for potential biases and demographic representation. Model cards provide a structured way to document the intended uses, performance characteristics, and ethical considerations of machine learning models.

This application focuses on the **data understanding** aspect of model card generation. Before a model can be built and documented, it is crucial to thoroughly understand the underlying dataset. This involves:

*   **Initial Data Exploration**: Getting a first look at the dataset's structure, summary statistics, and identifying missing values.
*   **Data Distribution Analysis**: Visualizing how numerical features are distributed, which can reveal skewness, outliers, or multimodal patterns.
*   **Demographic Representation**: Examining the proportions of different categories within demographic features to identify potential imbalances that could lead to biased model outcomes.
*   **Outlier Detection**: Using statistical plots to identify unusual data points that might impact model training.
*   **Feature Relationships**: Understanding how different features interact with each other, which is crucial for feature engineering and model interpretation.
*   **Bias Detection and Summary Insights**: A dedicated section to interpret findings and discuss potential biases, their impact on model performance, and mitigation strategies.

Understanding these aspects of your data is a foundational step in building responsible and fair AI systems. By providing an interactive platform, we aim to make this process intuitive and insightful for users.

All visualizations in this application are interactive and generated using **Plotly**, allowing for dynamic exploration of the data. We also extensively use `st.session_state` to maintain the application's state, ensuring a seamless user experience as you navigate through different analysis steps.
"""))
# Your code starts here
page = st.sidebar.selectbox(label="Navigation", options=["Data Loading & Exploration", "Distributions & Demographics", "Outliers & Relationships"])
if page == "Data Loading & Exploration":
    from application_pages.page1 import run_page1
    run_page1()
elif page == "Distributions & Demographics":
    from application_pages.page2 import run_page2
    run_page2()
elif page == "Outliers & Relationships":
    from application_pages.page3 import run_page3
    run_page3()
# Your code ends


# License
st.caption('''
---
## QuantUniversity License

© QuantUniversity 2025  
This notebook was created for **educational purposes only** and is **not intended for commercial use**.  

- You **may not copy, share, or redistribute** this notebook **without explicit permission** from QuantUniversity.  
- You **may not delete or modify this license cell** without authorization.  
- This notebook was generated using **QuCreate**, an AI-powered assistant.  
- Content generated by AI may contain **hallucinated or incorrect information**. Please **verify before using**.  

All rights reserved. For permissions or commercial licensing, contact: [info@qusandbox.com](mailto:info@qusandbox.com)
''')
